version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_ENV: prod  # Pass build arguments to the Dockerfile
    ports:
      - "3001:3001" # Map the container's port 3001 to the host's port 3001
    environment:
      - REACT_APP_ENV=prod # Environment variables passed at runtime
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Mount custom Nginx configuration
      - ./build:/usr/share/nginx/html # Mount the built app locally (optional)
